nome = input('Digite um valor: ')
print('O tipo primitivo desse valor é: ', type(nome))
print('Ele é númerico? ', nome.isnumeric())
print('Ele é Alfabético? ',nome.isalpha())
print('Ele é Alfanúmerico? ',nome.isalnum())
print('Ele está em maiusculo? ',nome.isupper())
print('Ele está em minusculos? ',nome.islower())
print('Ele é um espaço? ',nome.isspace())
print('Ele está capitalizada? ',nome.istitle())
